name: CCAdmin Gerar vers√£o

on:
  workflow_dispatch: # Roda apenas manualmente pelo painel do GitHub
    inputs:
      #version:
      #  description: 'Vers√£o do build'
      #  required: true
      #  default: '1.0.0'
      android:
        description: "Gerar vers√£o Android?"
        default: true
        type: boolean
      ios:
        description: "Gerar vers√£o iOS?"
        default: false
        type: boolean
      email:
        description: "Deseja enviar email ao finalizar?"
        default: true
        type: boolean

env:
  VERSION: ${{vars.VERSAO}}
  BUILD: ${{vars.build}}
  SENHA_CERTIFICADO_CLOUDFY: ${{ secrets.SENHA_CERTIFICADO_CLOUDFY }}
  SHOREBIRD_TOKEN: ${{ secrets.SHOREBIRD_KEY }}
  SIGNATURE_APP_ID: ${{ secrets.SIGNATURE_APP_ID }}
  SIGNATURE_CERTIFICATE_NAME: ${{ secrets.SIGNATURE_CERTIFICATE_NAME }}
  SIGNATURE_VAULT_ID: ${{ secrets.SIGNATURE_VAULT_ID }}
  SIGNATURE_PASSWORD: ${{ secrets.SIGNATURE_PASSWORD }}
  SIGNATURE_TENANT_ID: ${{ secrets.SIGNATURE_TENANT_ID }}

jobs:
  android:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    defaults:
      run:
        working-directory: ./flutter/adm

    steps:
      - name: Gerar Vari√°veis de Ambiente
        working-directory: .
        id: compute
        run: |
          echo 'DeployName=prod' >> $GITHUB_ENV
          echo 'DeployNameUpperCase=AdmAndroid' >> $GITHUB_ENV
          echo 'UrlId=18' >> $GITHUB_ENV
          VARIABLE=${{ github.event.inputs.android }}

          # Converte string para 0/1
          if [ "$VARIABLE" = "true" ]; then VARIABLE_BOOL=1; else VARIABLE_BOOL=0; fi          


          # OR l√≥gico
          if [ $((VARIABLE_BOOL)) -eq 1 ]; then
            EXECUTE=true
          else
            EXECUTE=false
          fi

          echo "Valor do execute: $EXECUTE"

          echo "execute=$EXECUTE" >> $GITHUB_OUTPUT
      # Clonar o reposit√≥rio principal do Flutter
      - uses: actions/checkout@v4
        if: ${{ (steps.compute.outputs.execute == 'true') }}
        with:
          repository: cloudfysystems/FLUTTER
          ref: main
          token: ${{ secrets.GH_TOKEN }}
          path: flutter

      # Clonar o reposit√≥rio de vers√£o
      - uses: actions/checkout@v4
        if: ${{ (steps.compute.outputs.execute == 'true') }}
        with:
          path: version-repo

      # Ler e atualizar a vers√£o
      - name: Ler vers√£o atual
        if: ${{ (steps.compute.outputs.execute == 'true') }}
        working-directory: version-repo
        shell: bash
        run: |
          VERSION_FILE="version${{env.DeployNameUpperCase}}.json"

          # Atualiza o JSON corretamente
          jq '.speedy.build += 1 | .speedy.version += 1 | .speedy.patch = 0' "$VERSION_FILE" > tmp.json

          mv tmp.json "$VERSION_FILE"

          # Pega os valores ap√≥s a atualiza√ß√£o
          BUILD=$(jq -r '.speedy.build' "$VERSION_FILE")
          VERSION=$(jq -r '.speedy.version' "$VERSION_FILE")
          SIMPLE=$(jq -r '.speedy.simple' "$VERSION_FILE")

          echo "Versao Build: $BUILD"
          echo "Versao Version: $VERSION"
          echo "Versao Gerada: $SIMPLE.$VERSION.0"

          echo "VERSAO=$SIMPLE.$VERSION.0" >> $GITHUB_ENV
          echo "VERSAO_BUILD=$BUILD" >> $GITHUB_ENV

          echo "Novo JSON:"
          cat "$VERSION_FILE"

      # Criar arquivo .jks a partir de base64
      - name: Criar arquivo .jks
        if: ${{ (steps.compute.outputs.execute == 'true') }}
        shell: bash
        run: |
          mkdir -p certificado
          echo "${{ secrets.KEYSTORE }}" | base64 -d > certificado/certificado-keystore.jks

      # Setup Shorebird
      - name: üê¶ Setup Shorebird
        if: ${{ (steps.compute.outputs.execute == 'true') }}
        uses: shorebirdtech/setup-shorebird@v1
        with:
          cache: true

      # Criar arquivo key.properties
      - name: Criar arquivo key.properties
        if: ${{ (steps.compute.outputs.execute == 'true') }}
        shell: bash
        run: |
          echo "storePassword=${{ secrets.SENHA_KEYSTORE }}" > android/key.properties
          echo "keyPassword=${{ secrets.SENHA_KEYSTORE }}" >> android/key.properties
          echo "keyAlias=cloudfycardapio" >> android/key.properties
          echo "storeFile=../../certificado/certificado-keystore.jks" >> android/key.properties

      # Set Up Java (usando Oracle JDK 17)
      - name: Set Up Java
        if: ${{ (steps.compute.outputs.execute == 'true') }}
        uses: actions/setup-java@v3
        with:
          distribution: "oracle"
          java-version: "17"

      # Atualizar vers√£o no arquivo Dart
      - name: Atualiza vers√£o no arquivo Dart e pubspec.yaml
        if: ${{ (steps.compute.outputs.execute == 'true') }}
        shell: bash
        run: |
          sed -i "s/^version:.*/version: $VERSAO+${{ env.VERSAO_BUILD }}/" pubspec.yaml
          cat pubspec.yaml

      # Executar build do Shorebird
      - name: üöÄ Shorebird Release
        if: ${{ (steps.compute.outputs.execute == 'true') }}
        id: shorebird-release
        uses: shorebirdtech/shorebird-release@v1
        with:
          args: --target lib/main_prod.dart --artifact apk
          platform: android
          flutter-version: ${{vars.FLUTTER_VERSION_SDK_ANDROID_SMART}}
          working-directory: ./flutter/adm

      - name: Renomear arquivos Android
        if: ${{ (steps.compute.outputs.execute == 'true') }}
        working-directory: .
        run: |
          echo "Renomeando APK"
          if [ -f "flutter/adm/build/app/outputs/flutter-apk/app-release.apk" ]; then
            mv flutter/adm/build/app/outputs/flutter-apk/app-release.apk flutter/adm/build/app/outputs/flutter-apk/CloudfyAdmAndroid.apk
            echo "APK renomeado para CloudfyAdmAndroid.apk"
          else
            echo "‚ö†Ô∏è APK n√£o encontrado!"
          fi

          echo "Renomeando AAB"
          if [ -f "flutter/adm/build/app/outputs/bundle/release/app-release.aab" ]; then
            mv flutter/adm/build/app/outputs/bundle/release/app-release.aab flutter/adm/build/app/outputs/bundle/release/CloudfyAdmAndroid.aab
            echo "AAB renomeado para CloudfyAdmAndroid.aab"
          else
            echo "‚ö†Ô∏è AAB n√£o encontrado!"
          fi

      - name: Criando o release
        if: ${{ (steps.compute.outputs.execute == 'true') }}
        uses: softprops/action-gh-release@v1
        with:
          tag_name: v${{ env.VERSAO }}_Adm${{env.DeployNameUpperCase}}
          name: v${{ env.VERSAO }}_Adm${{env.DeployNameUpperCase}}
          files: |
            flutter/adm/build/app/outputs/flutter-apk/CloudfyAdmAndroid.apk
            flutter/adm/build/app/outputs/bundle/release/CloudfyAdmAndroid.aab
          body: Release gerado automaticamente.
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}

      - name: Chamar API de altera√ß√£o de dados android
        if: ${{ (steps.compute.outputs.execute == 'true') }}
        run: |
          URLANDROID="https://github.com/cloudfysystems/Version/releases/download/v${{ env.VERSAO }}_Adm${{env.DeployNameUpperCase}}/CloudfyAdmAndroid.apk"
          echo "$URLANDROID"
          echo "Chamando API de valida√ß√£o..."

          JSON_DATA=$(cat <<EOF
          {
            "JSON": true,
            "Parameters": {
              "Versao": "${{ env.VERSAO }}",
              "PSW": "${{ secrets.SENHA_API_ALTERAR_URL }}",
              "URL": "$URLANDROID",
              "NR_ID": ${{ env.UrlId }}
            }
          }
          EOF
          )

          echo $JSON_DATA

          response=$(curl -s -o response.txt -w "%{http_code}" \
            -X POST https://api.cloudfy.net.br/H02SF0107A \
            -H "Content-Type: application/json" \
            -d "$JSON_DATA")

          echo "C√≥digo HTTP: $response"
          cat response.txt

          if [ "$response" != "200" ]; then
            echo "‚ùå Falha na chamada da API. Abortando workflow."
            exit 1
          fi

      - name: Atualizar branch com merge (se necess√°rio)
        if: ${{ (steps.compute.outputs.execute == 'true') }}
        working-directory: version-repo
        run: |
          git config user.name "cloudfysystems"
          git config user.email "cloudfysystems@gmail.com"

          # Garante que estamos na branch correta
          git branch --show-current

          # Tenta fazer pull e merge autom√°tico
          git pull origin HEAD --no-rebase || true
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}

      - name: Commit das altera√ß√µes
        uses: EndBug/add-and-commit@v9
        if: ${{ (steps.compute.outputs.execute == 'true') }}
        with:
          author_name: cloudfysystems
          author_email: cloudfysystems@gmail.com
          message: "alterada vers√£o do build ${{env.DeployNameUpperCase}}"
          cwd: ./version-repo
          add: "version${{env.DeployNameUpperCase}}.json"
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
  ios:
    runs-on: macos-latest
    permissions:
      contents: write
    defaults:
      run:
        working-directory: ./flutter/speed

    steps:
      # Clonar o reposit√≥rio principal do Flutter
      - uses: actions/checkout@v4
        if: ${{ inputs.ios}}
        with:
          repository: cloudfysystems/FLUTTER
          ref: main
          token: ${{ secrets.GH_TOKEN }}
          path: flutter

      # Clonar o reposit√≥rio de vers√£o
      - uses: actions/checkout@v4
        if: ${{ inputs.ios}}
        with:
          path: version-repo

      # Ler e atualizar a vers√£o
      - name: Ler vers√£o atual
        if: ${{ inputs.ios}}
        working-directory: version-repo
        shell: bash
        run: |
          VERSION_FILE="versionIOS.json"

          # Atualiza o JSON corretamente
          jq '.speedy.build += 1 | .speedy.version += 1 | .speedy.patch = 0' "$VERSION_FILE" > tmp.json

          mv tmp.json "$VERSION_FILE"

          # Pega os valores ap√≥s a atualiza√ß√£o
          BUILD=$(jq -r '.speedy.build' "$VERSION_FILE")
          VERSION=$(jq -r '.speedy.version' "$VERSION_FILE")
          SIMPLE=$(jq -r '.speedy.simple' "$VERSION_FILE")

          echo "Versao Build: $BUILD"
          echo "Versao Version: $VERSION"
          echo "Versao Gerada: $SIMPLE.$VERSION.0"

          echo "VERSAO=$SIMPLE.$VERSION.0" >> $GITHUB_ENV
          echo "VERSAO_BUILD=$BUILD" >> $GITHUB_ENV

          echo "Novo JSON:"
          cat "$VERSION_FILE"

      # Criar o arquivo env/prod.json
      - name: Gerar env/prod.json
        if: ${{ inputs.ios}}
        run: |
          mkdir -p ./env
          echo '${{ secrets.ENV_PROD }}' > ./env/prod.json
          cat ./env/prod.json

      - name: Import code sign
        if: ${{ inputs.ios}}
        uses: Apple-Actions/import-codesign-certs@v1
        with:
          p12-file-base64: ${{ secrets.APPLE_CERT_BASE64 }}
          p12-password: ${{ secrets.APPLE_CERT_PSW }}

      - name: Download provisioning
        if: ${{ inputs.ios}}
        uses: Apple-Actions/download-provisioning-profiles@v1
        with:
          bundle-id: com.cloudfy.speed
          issuer-id: ${{ secrets.APPLE_API_ISSUER_ID }}
          api-key-id: ${{ secrets.APPLE_API_KEY }}
          api-private-key: ${{ secrets.APPLE_API_PRIVATE_KEY }}
      - name: Configure Auth Key
        if: ${{ inputs.ios}}
        run: |
          mkdir -p ~/.appstoreconnect/private_keys
          echo "${{ secrets.APPLE_API_PRIVATE_KEY }}" > ~/.appstoreconnect/private_keys/AuthKey_${{ secrets.APPLE_API_KEY }}.p8
          chmod 600 ~/.appstoreconnect/private_keys/AuthKey_${{ secrets.APPLE_API_KEY }}.p8

      # Atualizar vers√£o no arquivo Dart
      - name: Atualiza vers√£o no arquivo Dart e pubspec.yaml
        if: ${{ inputs.ios }}
        shell: bash
        run: |
          FILE="lib/Environment/Version.dart"
          NOVA_VERSAO="${{ env.VERSAO }}"
              
          # Atualiza Version.dart
          sed -i '' "s/const String Version = \".*\"/const String Version = \"$NOVA_VERSAO\"/" "$FILE"
          cat "$FILE"
              
          # Atualiza pubspec.yaml
          sed -i '' "s/^version:.*/version: $VERSAO+${{ env.VERSAO_BUILD }}/" pubspec.yaml
          cat pubspec.yaml
      # Setup Shorebird
      - name: üê¶ Setup Shorebird
        if: ${{ inputs.ios}}
        uses: shorebirdtech/setup-shorebird@v1
        with:
          cache: true

      # Executar build do Shorebird
      - name: üöÄ Shorebird Release
        if: ${{ inputs.ios}}
        id: shorebird-release
        uses: shorebirdtech/shorebird-release@v1
        with:
          args: --export-options-plist ios/GHAExportOptions.plist -- --dart-define-from-file=env/prod.json
          platform: ios
          flutter-version: ${{vars.FLUTTER_VERSION_SDK_ANDROID_SMART}}
          working-directory: ./flutter/speed

      - name: Renomear arquivos iOS
        if: ${{ inputs.ios}}
        working-directory: .
        run: |
          echo "Renomeando IPA"
          if [ -f "flutter/speed/build/ios/ipa/speed.ipa" ]; then
            mv flutter/speed/build/ios/ipa/speed.ipa flutter/speed/build/ios/ipa/CloudfySpeedyPos.ipa
            echo "IPA renomeado para CloudfySpeedyPos.ipa"
          else
            echo "‚ö†Ô∏è IPA n√£o encontrado!"
          fi

      - name: Criando o release
        if: ${{ inputs.ios}}
        uses: softprops/action-gh-release@v1
        with:
          tag_name: v${{ env.VERSAO }}_SpeedyIOS
          name: v${{ env.VERSAO }}_SpeedyIOS
          files: |
            flutter/speed/build/ios/ipa/CloudfySpeedyPos.ipa
          body: Release gerado automaticamente.
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}

      - name: Chamar API de altera√ß√£o de dados android
        if: ${{ inputs.ios}}
        run: |
          URLIOS="https://github.com/cloudfysystems/Version/releases/download/v${{ env.VERSAO }}_SpeedyIOS/CloudfySpeedyPos.ipa"
          echo "$URLIOS"
          echo "Chamando API de valida√ß√£o..."

          JSON_DATA=$(cat <<EOF
          {
            "JSON": true,
            "Parameters": {
              "Versao": "${{ env.VERSAO }}",
              "PSW": "${{ secrets.SENHA_API_ALTERAR_URL }}",
              "URL": "$URLIOS",
              "NR_ID": 16
            }
          }
          EOF
          )

          echo $JSON_DATA

          response=$(curl -s -o response.txt -w "%{http_code}" \
            -X POST https://api.cloudfy.net.br/H02SF0107A \
            -H "Content-Type: application/json" \
            -d "$JSON_DATA")

          echo "C√≥digo HTTP: $response"
          cat response.txt

          if [ "$response" != "200" ]; then
            echo "‚ùå Falha na chamada da API. Abortando workflow."
            exit 1
          fi

      - name: Atualizar branch com merge (se necess√°rio)
        if: ${{ inputs.ios}}
        working-directory: version-repo
        run: |
          git config user.name "cloudfysystems"
          git config user.email "cloudfysystems@gmail.com"

          # Garante que estamos na branch correta
          git branch --show-current

          # Tenta fazer pull e merge autom√°tico
          git pull origin HEAD --no-rebase || true
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}

      - name: Commit das altera√ß√µes
        uses: EndBug/add-and-commit@v9
        if: ${{ inputs.ios}}
        with:
          author_name: cloudfysystems
          author_email: cloudfysystems@gmail.com
          message: "alterada vers√£o do build IOS"
          cwd: ./version-repo
          add: "versionIOS.json"
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}

      - name: Upload IPA to App Store Connect
        if: ${{ inputs.ios}}
        run: xcrun altool --upload-app --type ios -f ./build/ios/ipa/CloudfySpeedyPos.ipa --apiKey ${{ secrets.APPLE_API_KEY }} --apiIssuer ${{ secrets.APPLE_API_ISSUER_ID }}
  #Job que vai atualizar o git, sincronizar os fontes
  FinishJob:
    needs: [android, ios]
    runs-on: ubuntu-latest
    permissions:
      contents: write
    defaults:
      run:
        working-directory: ./flutterrepo

    steps:
      - name: Calculando a combina√ß√£o dos booleans Android
        id: compute
        working-directory: .
        run: |
          ANDROID=${{ github.event.inputs.android }}          
          IOS=${{ github.event.inputs.ios }}



          # Converte string para 0/1
          if [ "$ANDROID" = "true" ]; then ANDROID_BOOL=1; else ANDROID_BOOL=0; fi                    
          if [ "$IOS" = "true" ]; then IOS_BOOL=1; else IOS_BOOL=0; fi          


          # OR l√≥gico
          if [ $((ANDROID_BOOL | IOS_BOOL)) -eq 1 ]; then
            COMBINED=true
          else
            COMBINED=false
          fi

          echo "combined=$COMBINED" >> $GITHUB_OUTPUT
      - uses: actions/checkout@v4
        if: ${{ (steps.compute.outputs.combined == 'true') }}
        with:
          repository: cloudfysystems/FLUTTER
          fetch-depth: 0
          ref: main
          token: ${{ secrets.GH_TOKEN }}
          path: flutterrepo

      - uses: actions/checkout@v4
        if: ${{ (steps.compute.outputs.combined == 'true') }}
        with:
          path: version-repo

      - name: Recuperando os commits entre produ√ß√£o e main
        id: log
        if: ${{ (steps.compute.outputs.combined == 'true') }}
        continue-on-error: true
        run: |
          git config --global user.name "cloudfysystems"
          git config --global user.email "cloudfysystem@gmail.com"
          git config --global pull.rebase false
          git pull origin production
          commits=$(git log origin/production..origin/main --pretty=format:"- %s (%an)<br>" --no-merges)
          {
            echo "commit_messages<<EOF"
            echo "$commits"
            echo "EOF"
          } >> $GITHUB_OUTPUT
          git checkout production
          git merge origin/main --no-ff -m "gerando versao na falcatrua" --allow-unrelated-histories
          git push origin production

      - name: Envia e-mail com resumo
        uses: dawidd6/action-send-mail@v3
        #if: ${{ steps.compute.outputs.combined == 'true' && github.event.inputs.email}}
        if: false
        with:
          server_address: mail.cloudfy.net.br
          server_port: 465
          username: ${{ secrets.EMAIL_USER }}
          password: ${{ secrets.EMAIL_PASS }}
          subject: "CC Admin - Gerado vers√£o em produ√ß√£o"
          html_body: |
            <p><b>Ol√° time!</b></p>


            Foi gerada uma nova vers√£o em produ√ß√£o do CCAdmin!<br><br>
              
            Commits inclu√≠dos:<br><br>
              
            <b>${{ steps.log.outputs.commit_messages }}</b><br><br>
              
            <p>Os novos arquivos est√£o dispon√≠veis na √°rea de download</p>
              
            <p><b>Menos foco, mais ansiedade!</b></p>
          to: ${{ vars.EMAIL }}
          from: Cloudfy Vers√£o <noreply@cloudfy.net.br>
          secure: true
