name: SpeedyPos Patch

on:
  workflow_dispatch: # Roda apenas manualmente pelo painel do GitHub
    inputs:
      #version:
      #  description: 'Vers√£o do build'
      #  required: true
      #  default: '1.0.0'
      windows:
        description: "Atualizar vers√£o Windows (Patch)?"
        default: true
        type: boolean
      android-prod:
        description: "Atualizar vers√£o Android (Patch)?"
        default: true
        type: boolean
      android-tef:
        description: "Atualizar vers√£o Android(TEF)? (Patch)"
        default: true
        type: boolean
      android-pagseguro:
        description: "Atualizar vers√£o Android(PagSeguro)? (Patch)"
        default: false
        type: boolean
      android-getnet:
        description: "Atualizar vers√£o Android(Getnet)? (Patch)"
        default: false
        type: boolean
      android-cielo:
        description: "Atualizar vers√£o Android(Cielo)? (Patch)"
        default: false
        type: boolean
      android-rede:
        description: "Atualizar vers√£o Android(Rede)? (Patch)"
        default: false
        type: boolean
      ios:
        description: "Atualizar vers√£o iOS? (Patch)"
        default: false
        type: boolean
env:
  VERSION: ${{vars.VERSAO}}
  BUILD: ${{vars.build}}
  SENHA_CERTIFICADO_CLOUDFY: ${{ secrets.SENHA_CERTIFICADO_CLOUDFY }}
  SHOREBIRD_TOKEN: ${{ secrets.SHOREBIRD_KEY }}
  SIGNATURE_APP_ID: ${{ secrets.SIGNATURE_APP_ID }}
  SIGNATURE_CERTIFICATE_NAME: ${{ secrets.SIGNATURE_CERTIFICATE_NAME }}
  SIGNATURE_VAULT_ID: ${{ secrets.SIGNATURE_VAULT_ID }}
  SIGNATURE_PASSWORD: ${{ secrets.SIGNATURE_PASSWORD }}
  SIGNATURE_TENANT_ID: ${{ secrets.SIGNATURE_TENANT_ID }}

jobs:
  Windows-update:
    runs-on: windows-latest

    defaults:
      run:
        working-directory: ./flutter/speed
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4
        if: ${{ inputs.windows }}
        with:
          repository: cloudfysystems/FLUTTER
          ref: main # ou a branch/tag desejada
          token: ${{ secrets.GH_TOKEN }}
          path: flutter

      # checkout do repositorio de vers√£o
      - uses: actions/checkout@v4
        if: ${{ inputs.windows }}
        with:
          path: version-repo
        # Lendo a vers√£o atual do reposit√≥rio
      - name: Ler vers√£o atual
        if: ${{ inputs.windows }}
        working-directory: version-repo
        shell: powershell
        run: |
          $json = Get-Content "versionWindows.json" | ConvertFrom-Json          
          $json.speedy.patch++

          # Salva de volta no JSON
          $json | ConvertTo-Json -Depth 10 | Out-File -FilePath "versionWindows.json" -Encoding UTF8
          echo "Versao gerada: $($json.speedy.simple).$($json.speedy.version).$($json.speedy.patch)"
          echo "VERSAOOLD=$($json.speedy.simple).$($json.speedy.version).0" >> $env:GITHUB_ENV
          echo "VERSAO=$($json.speedy.simple).$($json.speedy.version).$($json.speedy.patch)" >> $env:GITHUB_ENV

      - name: Gerando o env/prod.json
        if: ${{ inputs.windows }}
        run: |
          New-Item -ItemType Directory -Path "./env" -Force | Out-Null
          Set-Content -Path "./env/prod.json" -Value '${{ secrets.ENV_PROD }}'
        shell: pwsh
      - name: Atualiza vers√£o no arquivo Dart
        if: ${{ inputs.windows }}
        shell: pwsh
        run: |
          $filePath = "lib/Environment/Version.dart"
          $novaVersao = "${{ env.VERSAO }}"  # ou outro valor din√¢mico
          (Get-Content $filePath) -replace 'const String Version = ".*?"', "const String Version = `"$novaVersao`"" | Set-Content $filePath

      # Set Up Java (O Sentry precisa do java para compilar)
      - name: Set Up Java
        if: ${{ inputs.windows }}
        uses: actions/setup-java@v3
        with:
          distribution: "oracle"
          java-version: "17"
      - name: Ajeitar o longpath do git
        if: ${{ inputs.windows }}
        run: |
          git config --system core.longpaths true
      - name: üê¶ Setup Shorebird
        if: ${{ inputs.windows }}
        uses: shorebirdtech/setup-shorebird@v1
        with:
          cache: true

      #- name: Mostrar caminho e conte√∫do do prod.json
      #  run: |
      #      $filePath = Resolve-Path "./env/prod.json"
      #      Write-Host "üìÅ Caminho do arquivo: $filePath"
      #      Write-Host "üìÑ Conte√∫do do arquivo:"
      #      Get-Content $filePath | ForEach-Object { Write-Host $_ }
      #  shell: pwsh
      #

      - name: Gerar Patch windows
        uses: shorebirdtech/shorebird-patch@v1
        id: shorebird-patch
        if: ${{ inputs.windows }}
        with:
          platform: windows
          args: --allow-asset-diffs -- --dart-define-from-file=env/prod.json
          release-version: ${{env.VERSAOOLD}}
          working-directory: ./flutter/speed

      - name: Chamar API de altera√ß√£o de dados windows
        if: ${{ inputs.windows }}
        id: api_call_windows
        run: |
          Write-Host "Chamando API de valida√ß√£o..."

          # Monta o JSON usando Here-String
          $JSON_DATA = @"
          {
            "JSON": true,
            "Parameters": {
              "Versao": "${{ env.VERSAO }}",
              "PSW": "${{ secrets.SENHA_API_ALTERAR_URL }}",              
              "NR_ID": 4
            }
          }
          "@

          Write-Host "JSON enviado:"
          Write-Host $JSON_DATA

          # Executa o CURL
          $response = curl -s -o response.txt -w "%{http_code}" `
            -X POST https://api.cloudfy.net.br/H02SF0107A `
            -H "Content-Type: application/json" `
            -d $JSON_DATA

          Write-Host "C√≥digo HTTP: $response"

          # Mostra o retorno
          Get-Content response.txt

          if ($response -ne "200") {
            Write-Host "‚ùå Falha na chamada da API. Abortando workflow."
            exit 1
          }
      - name: Atualizar branch com merge (se necess√°rio)
        if: ${{ inputs.windows }}
        working-directory: version-repo
        run: |
          git config user.name "cloudfysystems"
          git config user.email "cloudfysystems@gmail.com"

          # Garante que estamos na branch correta
          git branch --show-current

          # Tenta fazer pull e merge autom√°tico
          git pull origin HEAD --no-rebase || true
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}

      - name: Commit das altera√ß√µes
        uses: EndBug/add-and-commit@v9
        if: ${{ inputs.windows }}
        with:
          author_name: cloudfysystems
          author_email: cloudfysystems@gmail.com
          message: "alterada vers√£o do build windows"
          cwd: ./version-repo
          add: "versionWindows.json"
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
  Android-update:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./flutter/speed

    steps:
      - name: Calculando a combina√ß√£o dos booleans Android
        id: compute
        working-directory: .
        run: |
          ANDROID=${{ github.event.inputs.android-update }}
          TEF=${{ github.event.inputs.android-tef-update }}
          PAGSEGURO=${{ github.event.inputs.android-pagseguro }}

          # Converte string para 0/1
          if [ "$ANDROID" = "true" ]; then ANDROID_BOOL=1; else ANDROID_BOOL=0; fi
          if [ "$TEF" = "true" ]; then TEF_BOOL=1; else TEF_BOOL=0; fi
          if [ "$PAGSEGURO" = "true" ]; then PAGSEGURO_BOOL=1; else PAGSEGURO_BOOL=0; fi

          # OR l√≥gico
          if [ $((ANDROID_BOOL | TEF_BOOL | PAGSEGURO_BOOL)) -eq 1 ]; then
            COMBINED=true
          else
            COMBINED=false
          fi

          echo "combined=$COMBINED" >> $GITHUB_OUTPUT
      # Clonar o reposit√≥rio principal do Flutter
      - uses: actions/checkout@v4
        if: ${{ steps.compute.outputs.combined == 'true' }}
        with:
          repository: cloudfysystems/FLUTTER
          ref: main
          token: ${{ secrets.GH_TOKEN }}
          path: flutter

      # Clonar o reposit√≥rio de vers√£o
      - uses: actions/checkout@v4
        if: ${{ steps.compute.outputs.combined == 'true' }}
        with:
          path: version-repo

      # Ler e atualizar a vers√£o
      - name: Ler vers√£o atual (prod)
        if: ${{ inputs.android-update }}
        working-directory: version-repo
        shell: bash
        run: |
          VERSION_FILE="version.json"
          BUILD=$(jq '.speedyAndroid.build' $VERSION_FILE)
          VERSION=$(jq '.speedyAndroid.version' $VERSION_FILE)
          SIMPLE=$(jq -r '.speedyAndroid.simple' $VERSION_FILE)
          PATCH=$(jq -r '.speedyAndroid.patch += 1 | .speedyAndroid.patch' $VERSION_FILE)
          echo "Versao Build: $BUILD"
          echo "Versao Version: $VERSION"
          echo "Versao Gerada: $SIMPLE.$VERSION.0"
          echo "VERSAO=$SIMPLE.$VERSION.$PATCH+$BUILD" >> $GITHUB_ENV
          echo "VERSAOOLD=$SIMPLE.$VERSION.0+$BUILD" >> $GITHUB_ENV

      - name: Ler vers√£o atual (tef)
        if: ${{ inputs.android-tef-update }}
        working-directory: version-repo
        shell: bash
        run: |
          VERSION_FILE="version.json"
          BUILD=$(jq '.speedyAndroidTef.build' $VERSION_FILE)
          VERSION=$(jq '.speedyAndroidTef.version' $VERSION_FILE)
          SIMPLE=$(jq -r '.speedyAndroidTef.simple' $VERSION_FILE)
          PATCH=$(jq -r '.speedyAndroidTef.patch += 1 | .speedyAndroidTef.patch' $VERSION_FILE)
          echo "Versao tef Build: $BUILD"
          echo "Versao tef Version: $VERSION"
          echo "Versao tef Gerada: $SIMPLE.$VERSION.0"
          echo "VERSAOTEF=$SIMPLE.$VERSION.$PATCH+$BUILD" >> $GITHUB_ENV
          echo "VERSAOTEFOLD=$SIMPLE.$VERSION.0-tef+$BUILD" >> $GITHUB_ENV

      - name: Ler vers√£o atual (pagseguro)
        if: ${{ inputs.android-pagseguro }}
        working-directory: version-repo
        shell: bash
        run: |
          VERSION_FILE="version.json"
          BUILD=$(jq '.speedyAndroidPagSeguro.build' $VERSION_FILE)
          VERSION=$(jq '.speedyAndroidPagSeguro.version' $VERSION_FILE)
          SIMPLE=$(jq -r '.speedyAndroidPagSeguro.simple' $VERSION_FILE)
          PATCH=$(jq -r '.speedyAndroidPagSeguro.patch += 1 | .speedyAndroidPagSeguro.patch' $VERSION_FILE)
          echo "Versao tef Build: $BUILD"
          echo "Versao tef Version: $VERSION"
          echo "Versao tef Gerada: $SIMPLE.$VERSION.0"
          echo "VERSAOPAGSEGURO=$SIMPLE.$VERSION.$PATCH+$BUILD" >> $GITHUB_ENV
          echo "VERSAOPAGSEGUROOLD=$SIMPLE.$VERSION.0-pagseguro+$BUILD" >> $GITHUB_ENV

      # Criar o arquivo env/prod.json
      - name: Gerar env/prod.json
        if: ${{ steps.compute.outputs.combined == 'true' }}
        run: |
          mkdir -p ./env
          echo '${{ secrets.ENV_PROD }}' > ./env/prod.json
          cat ./env/prod.json

      # Criar arquivo .jks a partir de base64
      - name: Criar arquivo .jks
        if: ${{ steps.compute.outputs.combined == 'true' }}
        shell: bash
        run: |
          mkdir -p certificado
          echo "${{ secrets.KEYSTORE }}" | base64 -d > certificado/certificado-keystore.jks

      # Setup Shorebird
      - name: üê¶ Setup Shorebird
        if: ${{ steps.compute.outputs.combined == 'true' }}
        uses: shorebirdtech/setup-shorebird@v1
        with:
          cache: true

      # Criar arquivo key.properties
      - name: Criar arquivo key.properties
        if: ${{ steps.compute.outputs.combined == 'true' }}
        shell: bash
        run: |
          echo "storePassword=${{ secrets.SENHA_KEYSTORE }}" > android/key.properties
          echo "keyPassword=${{ secrets.SENHA_KEYSTORE }}" >> android/key.properties
          echo "keyAlias=cloudfycardapio" >> android/key.properties
          echo "storeFile=../../certificado/certificado-keystore.jks" >> android/key.properties

      # Set Up Java (usando Oracle JDK 17)
      - name: Set Up Java
        if: ${{ steps.compute.outputs.combined == 'true' }}
        uses: actions/setup-java@v3
        with:
          distribution: "oracle"
          java-version: "17"

        # Atualizar vers√£o no arquivo Dart
      - name: Atualiza vers√£o no arquivo Dart (prod)
        if: ${{ inputs.android-update }}
        shell: bash
        run: |
          FILE="lib/Environment/Version.dart"
          NOVA_VERSAO="${{ env.VERSAO }}"
          sed -i "s/const String Version = \".*\"/const String Version = \"$NOVA_VERSAO\"/" $FILE
          cat lib/Environment/Version.dart

      - name: Gerar Patch Android (Prod)
        uses: shorebirdtech/shorebird-patch@v1
        id: shorebird-patch
        if: ${{ inputs.android-update }}
        with:
          platform: android
          args: --allow-asset-diffs --flavor prod -- --dart-define-from-file=env/prod.json --dart-define=FLAVOR=prod
          release-version: ${{env.VERSAOOLD}}
          working-directory: ./flutter/speed

      # Atualizar vers√£o no arquivo Dart
      - name: Atualiza vers√£o no arquivo Dart (tef)
        if: ${{ inputs.android-tef-update }}
        shell: bash
        run: |
          FILE="lib/Environment/Version.dart"
          NOVA_VERSAO="${{ env.VERSAOTEF }}"
          sed -i "s/const String Version = \".*\"/const String Version = \"$NOVA_VERSAO\"/" $FILE
          cat lib/Environment/Version.dart

      - name: Gerar Patch Android (tef)
        uses: shorebirdtech/shorebird-patch@v1
        id: shorebird-patch-tef
        if: ${{ inputs.android-tef-update }}
        with:
          platform: android
          args: --allow-asset-diffs --flavor tef -- --dart-define-from-file=env/prod.json --dart-define=FLAVOR=tef
          release-version: ${{env.VERSAOTEFOLD}}
          working-directory: ./flutter/speed

      # Atualizar vers√£o no arquivo Dart
      - name: Atualiza vers√£o no arquivo Dart (pagseguro)
        if: ${{ inputs.android-pagseguro }}
        shell: bash
        run: |
          FILE="lib/Environment/Version.dart"
          NOVA_VERSAO="${{ env.VERSAOPAGSEGURO }}"
          sed -i "s/const String Version = \".*\"/const String Version = \"$NOVA_VERSAO\"/" $FILE
          cat lib/Environment/Version.dart

      - name: Gerar Patch Android (pagseguro)
        uses: shorebirdtech/shorebird-patch@v1
        id: shorebird-patch-pagseguro
        if: ${{ inputs.android-pagseguro }}
        with:
          platform: android
          args: --allow-asset-diffs --flavor pagseguro -- --dart-define-from-file=env/prod.json --dart-define=FLAVOR=pagseguro
          release-version: ${{env.VERSAOPAGSEGUROOLD}}
          working-directory: ./flutter/speed
  FinishJob-update:
    needs: [Android-update, Windows-update]
    runs-on: ubuntu-latest
    permissions:
      contents: write
    defaults:
      run:
        working-directory: ./flutterrepo

    steps:
      - name: Calculando a combina√ß√£o dos booleans Android
        id: compute
        working-directory: .
        run: |
          WINDOWS=${{ github.event.inputs.windows }}
          ANDROID=${{ github.event.inputs.android-prod }}
          TEF=${{ github.event.inputs.android-tef }}
          PAGSEGURO=${{ github.event.inputs.android-pagseguro }}
          GETNET=${{ github.event.inputs.android-getnet }}
          CIELO=${{ github.event.inputs.android-cielo }}
          REDE=${{ github.event.inputs.android-rede }}
          IOS=${{ github.event.inputs.ios }}



          # Converte string para 0/1
          if [ "$ANDROID" = "true" ]; then ANDROID_BOOL=1; else ANDROID_BOOL=0; fi
          if [ "$TEF" = "true" ]; then TEF_BOOL=1; else TEF_BOOL=0; fi
          if [ "$PAGSEGURO" = "true" ]; then PAGSEGURO_BOOL=1; else PAGSEGURO_BOOL=0; fi
          if [ "$GETNET" = "true" ]; then GETNET_BOOL=1; else GETNET_BOOL=0; fi
          if [ "$CIELO" = "true" ]; then CIELO_BOOL=1; else CIELO_BOOL=0; fi
          if [ "$REDE" = "true" ]; then REDE_BOOL=1; else REDE_BOOL=0; fi
          if [ "$WINDOWS" = "true" ]; then WINDOWS_BOOL=1; else WINDOWS_BOOL=0; fi
          if [ "$IOS" = "true" ]; then IOS_BOOL=1; else IOS_BOOL=0; fi


          # OR l√≥gico
          if [ $((ANDROID_BOOL | TEF_BOOL | PAGSEGURO_BOOL | GETNET_BOOL | CIELO_BOOL | REDE_BOOL | WINDOWS_BOOL | IOS_BOOL)) -eq 1 ]; then
            COMBINED=true
          else
            COMBINED=false
          fi

          echo "combined=$COMBINED" >> $GITHUB_OUTPUT

      - uses: actions/checkout@v4
        if: ${{ (steps.compute.outputs.combined == 'true') }}
        with:
          repository: cloudfysystems/FLUTTER
          fetch-depth: 0
          ref: main
          token: ${{ secrets.GH_TOKEN }}
          path: flutterrepo

      - uses: actions/checkout@v4
        if: ${{ (steps.compute.outputs.combined == 'true') }}
        with:
          path: version-repo

      - name: Recuperando os commits entre produ√ß√£o e main
        id: log
        if: ${{ (steps.compute.outputs.combined == 'true') }}
        continue-on-error: true
        run: |
          git config --global user.name "cloudfysystems"
          git config --global user.email "cloudfysystem@gmail.com"
          git config --global pull.rebase false
          git pull origin production
          commits=$(git log origin/production..origin/main --pretty=format:"- %s (%an)<br>" --no-merges)
          {
            echo "commit_messages<<EOF"
            echo "$commits"
            echo "EOF"
          } >> $GITHUB_OUTPUT
          git checkout production
          git merge origin/main --no-ff -m "gerando versao na falcatrua" --allow-unrelated-histories
          git push origin production

      - name: Envia e-mail com resumo
        uses: dawidd6/action-send-mail@v3
        if: ${{ (steps.compute.outputs.combined == 'true') }}
        with:
          server_address: mail.cloudfy.net.br
          server_port: 465
          username: ${{ secrets.EMAIL_USER }}
          password: ${{ secrets.EMAIL_PASS }}
          subject: "Speedy POS - Novo Patch gerado"
          html_body: |
            <p><b>Ol√° time!</b></p>

            Foi gerada um novo Patch para o speedy POS, na vers√£o ${{ env.VERSAO }}!<br><br>

            Essa atualiza√ß√£o ser√° enviada automaticamente para clientes que estejam na mesma
            vers√£o da aplica√ß√£o.

            Commits inclu√≠dos:<br><br>

            <b>${{ steps.log.outputs.commit_messages }}</b><br><br>            

            <p><b>Menos foco, mais ansiedade!</b></p>
          to: ${{ vars.EMAIL }}
          from: Cloudfy Vers√£o <noreply@cloudfy.net.br>
          secure: true
